export const primary: string;
export const dark: string;
export const border: string;
export const canvas: string;
export const background: string;
export const jellybeanRedLight: string;
export const jellybeanRed: string;
export const taupeGray: string;
export const darkVanilaGrey: string;
